### ISSUE TITLE
Put actual data on the website

### ISSUE THREAD

**Issue by samestep** [gradbench/gradbench#97]
Currently the website just shows a static table of blanks and checkmarks, which has fallen a bit out of date as we've done more work since #56. We should modify the website to take the data emitted by actually running each evaluation on each tool (see #92) and display it in a big table. Then there should be a way to drill down to an individual row or column to see more detailed visualizations.

This also relates to #95: currently we have a bunch of general exposition on the website, and I think we should remove that and move it to `README.md` and `CONTRIBUTING.md` in the repo itself. Then the website can be just a way to explore the data.

**Comment by athas** [comment]
Apart from the table showing completeness of implementations, what other "data" should be shown? ADBench has/had really lovely performance graphs, where in particular the Jacobian overhead graphs were very nice (e.g. Fig. 7 in https://arxiv.org/pdf/1807.10129). I would like GradBench to have the same, and I think it can be extracted from the log files (currently the evals don't do enough runs for the runtime numbers to be trustworthy, but that can be dealt with separately). Doing a prototype should be pretty simple. Any preference for plotting tech? ADBench used gnuplot IIRC.

**Comment by athas** [comment]
[Ah no, all matplotlib](https://github.com/diku-dk/ADBench/blob/master/ADBench/plot_graphs.py).

**Comment by samestep** [comment]
@athas yes, absolutely! That was what I meant by this sentence above:

> Then there should be a way to drill down to an individual row or column to see more detailed visualizations.

See #108 which added a script to generate a `summary.json` file for the table itself; I'd like to extend that same script to generate `tool-*.json` and `eval-*.json` files corresponding to all the rows and columns of the table, which will contain the timing data necessary to generate those plots.

Since we're going to be embedding these plots in the website, my tentative plan was to use [Vega-Lite](https://vega.github.io/vega-lite/), but I'm open to any vector plotting tool that will be easy to use in React, building off of #109.
